### ISSUE TITLE
Allocate Failure in readFromBMP

### ISSUE THREAD

**Issue by fouzhe** [thejinchao/jpeg_encoder#3]
I used **Clang 6.0 and AddressSanitizer**  to build **jpeg-encoder**, this [file](https://github.com/fouzhe/security/blob/master/jpeg_encoder/allocate_failure_readFromBMP) can cause allocate failure in function readFromBMP in jpeg_encoder.cpp when executing this command:

```shell
./a.out allocate_failure_readFromBMP
```

This is the ASAN information:

```shell
==7094==WARNING: AddressSanitizer failed to allocate 0xffffffffffa00000 bytes
==7094==AddressSanitizer's allocator is terminating the process instead of returning 0
==7094==If you don't like this behavior set allocator_may_return_null=1
==7094==AddressSanitizer CHECK failed: /home/fouzhe/llvm/llvm/projects/compiler-rt/lib/sanitizer_common/sanitizer_allocator.cc:225 "((0)) != (0)" (0x0, 0x0)
    #0 0x4e7d5f in __asan::AsanCheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) /home/fouzhe/llvm/llvm/projects/compiler-rt/lib/asan/asan_rtl.cc:69
    #1 0x504ce5 in __sanitizer::CheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) /home/fouzhe/llvm/llvm/projects/compiler-rt/lib/sanitizer_common/sanitizer_termination.cc:79
    #2 0x4edb86 in __sanitizer::ReportAllocatorCannotReturnNull() /home/fouzhe/llvm/llvm/projects/compiler-rt/lib/sanitizer_common/sanitizer_allocator.cc:225
    #3 0x4edbc3 in __sanitizer::ReturnNullOrDieOnFailure::OnBadRequest() /home/fouzhe/llvm/llvm/projects/compiler-rt/lib/sanitizer_common/sanitizer_allocator.cc:241
    #4 0x4248c7 in __asan::asan_memalign(unsigned long, unsigned long, __sanitizer::BufferedStackTrace*, __asan::AllocType) /home/fouzhe/llvm/llvm/projects/compiler-rt/lib/asan/asan_allocator.cc:900
    #5 0x516478 in operator new[](unsigned long) /home/fouzhe/llvm/llvm/projects/compiler-rt/lib/asan/asan_new_delete.cc:95
    #6 0x51c396 in JpegEncoder::readFromBMP(char const*) /home/fouzhe/my_fuzz/jpeg_encoder/jpeg_encoder.cpp:193:27
    #7 0x51a88b in main /home/fouzhe/my_fuzz/jpeg_encoder/test.cpp:16:14
    #8 0x7f3acf0b082f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #9 0x41a638 in _start (/home/fouzhe/my_fuzz/jpeg_encoder/a.out+0x41a638)
```

**Comment by thejinchao** [comment]
Thank you, but this code is just an introduction to the basic JPEG algorithm, and I definitely didn’t consider security too much.
