### ISSUE TITLE
SEGV in function readFromBMP

### ISSUE THREAD

**Issue by fouzhe** [thejinchao/jpeg_encoder#4]
I used **Clang 6.0 and AddressSanitizer**  to build **jpeg-encoder**, this [file](https://github.com/fouzhe/security/blob/master/jpeg_encoder/SEGV_readFromBMP) can cause SEGV in function readFromBMP when executing this command:

```shell
./a.out SEGV_readFromBMP
```

This is the ASAN information:

```shell
AddressSanitizer:DEADLYSIGNAL
=================================================================
==26187==ERROR: AddressSanitizer: SEGV on unknown address 0x602003000010 (pc 0x7f6485b4a3f2 bp 0x000000000018 sp 0x7ffe77d368f8 T0)
==26187==The signal is caused by a WRITE memory access.
    #0 0x7f6485b4a3f1  (/lib/x86_64-linux-gnu/libc.so.6+0x8f3f1)
    #1 0x7f6485b3403d  (/lib/x86_64-linux-gnu/libc.so.6+0x7903d)
    #2 0x7f6485b29235 in fread (/lib/x86_64-linux-gnu/libc.so.6+0x6e235)
    #3 0x49e7e6 in fread /home/fouzhe/llvm/llvm/projects/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:977
    #4 0x51c515 in JpegEncoder::readFromBMP(char const*) /home/fouzhe/my_fuzz/jpeg_encoder/jpeg_encoder.cpp:202:17
    #5 0x51a88b in main /home/fouzhe/my_fuzz/jpeg_encoder/test.cpp:16:14
    #6 0x7f6485adb82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #7 0x41a638 in _start (/home/fouzhe/my_fuzz/jpeg_encoder/a.out+0x41a638)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/lib/x86_64-linux-gnu/libc.so.6+0x8f3f1)
==26187==ABORTING
```

**Comment by thejinchao** [comment]
Thank you, but this code is just an introduction to the basic JPEG algorithm, and I definitely didn’t consider security too much.
