### ISSUE TITLE
SEGV in function _convertColorSpace

### ISSUE THREAD

**Issue by fouzhe** [thejinchao/jpeg_encoder#5]
I used **Clang 6.0 and AddressSanitizer**  to build **jpeg-encoder**, this [file](https://github.com/fouzhe/security/blob/master/jpeg_encoder/SEGV__convertColorSpace) can cause SEGV in function _convertColorSpace in jpeg_encoder.cpp when executing this command:

```shell
./a.out SEGV__convertColorSpace
```

This is the ASAN information:

```shell
AddressSanitizer:DEADLYSIGNAL
=================================================================
==1347==ERROR: AddressSanitizer: SEGV on unknown address 0x60ffc0000058 (pc 0x0000005201c0 bp 0x000000000000 sp 0x7fffa96a3330 T0)
==1347==The signal is caused by a READ memory access.
    #0 0x5201bf in JpegEncoder::_convertColorSpace(int, int, char*, char*, char*) /home/fouzhe/my_fuzz/jpeg_encoder/jpeg_encoder.cpp:471:22
    #1 0x51d671 in JpegEncoder::encodeToJPG(char const*, int) /home/fouzhe/my_fuzz/jpeg_encoder/jpeg_encoder.cpp:256:4
    #2 0x51a8e1 in main /home/fouzhe/my_fuzz/jpeg_encoder/test.cpp:21:14
    #3 0x7f60ad83082f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #4 0x41a638 in _start (/home/fouzhe/my_fuzz/jpeg_encoder/a.out+0x41a638)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/fouzhe/my_fuzz/jpeg_encoder/jpeg_encoder.cpp:471:22 in JpegEncoder::_convertColorSpace(int, int, char*, char*, char*)
==1347==ABORTING
```

**Comment by thejinchao** [comment]
Thank you, but this code is just an introduction to the basic JPEG algorithm, and I definitely didn’t consider security too much.
