### ISSUE TITLE
heap-buffer-overflow in function _convertColorSpace

### ISSUE THREAD

**Issue by fouzhe** [thejinchao/jpeg_encoder#7]
I used **Clang 6.0 and AddressSanitizer**  to build **jpeg-encoder**, this [file](https://github.com/fouzhe/security/blob/master/jpeg_encoder/heap_buffer_overflow__convertColorSpace) can cause heap-buffer-overflow in function _convertColorSpace in jpeg_encoder.cpp when executing this command:

```shell
./a.out heap_buffer_overflow__convertColorSpace
```

This is the ASAN information:

```shell
=================================================================
==3638==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x602000000011 at pc 0x000000522018 bp 0x7ffe3bab8540 sp 0x7ffe3bab8538
READ of size 1 at 0x602000000011 thread T0
    #0 0x522017 in JpegEncoder::_convertColorSpace(int, int, char*, char*, char*) /home/fouzhe/my_fuzz/jpeg_encoder/jpeg_encoder.cpp:472:22
    #1 0x51d671 in JpegEncoder::encodeToJPG(char const*, int) /home/fouzhe/my_fuzz/jpeg_encoder/jpeg_encoder.cpp:256:4
    #2 0x51a8e1 in main /home/fouzhe/my_fuzz/jpeg_encoder/test.cpp:21:14
    #3 0x7f7f579b782f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #4 0x41a638 in _start (/home/fouzhe/my_fuzz/jpeg_encoder/a.out+0x41a638)

0x602000000011 is located 0 bytes to the right of 1-byte region [0x602000000010,0x602000000011)
allocated by thread T0 here:
    #0 0x5164a8 in operator new[](unsigned long) /home/fouzhe/llvm/llvm/projects/compiler-rt/lib/asan/asan_new_delete.cc:95
    #1 0x51c396 in JpegEncoder::readFromBMP(char const*) /home/fouzhe/my_fuzz/jpeg_encoder/jpeg_encoder.cpp:193:27
    #2 0x51a88b in main /home/fouzhe/my_fuzz/jpeg_encoder/test.cpp:16:14
    #3 0x7f7f579b782f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/fouzhe/my_fuzz/jpeg_encoder/jpeg_encoder.cpp:472:22 in JpegEncoder::_convertColorSpace(int, int, char*, char*, char*)
Shadow bytes around the buggy address:
  0x0c047fff7fb0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c047fff7fc0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c047fff7fd0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c047fff7fe0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c047fff7ff0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c047fff8000: fa fa[01]fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8010: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8020: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8030: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8040: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff8050: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==3638==ABORTING
```

**Comment by thejinchao** [comment]
Thank you, but this code is just an introduction to the basic JPEG algorithm, and I definitely didn’t consider security too much.
